# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

variables:
  BUNDLE_PATH: $(Pipeline.Workspace)/.bundle

trigger:
- master

strategy:
  matrix:
    win-chrome:
      imageName: 'windows-2019'
      browser: chrome

pool:
  vmImage: $(imageName)

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: |
    gem install bundler
    bundle install
  workingDirectory: selenium-webdriver-rspec
  displayName: 'bundle install'

- script: bundle exec rake -f Rakefile ci:ui_tests:quick
  displayName: 'bundle exec rake'
  workingDirectory: selenium-webdriver-rspec
