# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

strategy:
  matrix:
    win-chrome:
      imageName: 'windows-2019'
      browser: chrome

pool:
  vmImage: $(imageName)

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- pwsh: |
   echo "##vso[task.prependpath]$env:CHROMEWEBDRIVER"
  displayName: Adds ChromeWebDriver for Selenium to PATH

- script: gem install bundler
  workingDirectory: selenium-webdriver-rspec
  displayName: 'bundler install'

- script: bundle install --gemfile=Gemfile
  workingDirectory: selenium-webdriver-rspec
  displayName: 'bundle install'

- script: bundle exec rake -f Rakefile ci:ui_tests:hello-world
  displayName: 'bundle exec rake'
  workingDirectory: selenium-webdriver-rspec
